/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import com.mycompany.mavenproject1.Mavenproject1;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
public class PanelGui extends javax.swing.JPanel {

    /**
     * Creates new form PanelGui
     */
    public PanelGui() {
        initComponents();
        try {
            UIManager.setLookAndFeel(new FlatLightLaf()); // Establecer el estilo FlatLaf
        } catch (Exception ex) {
            // Manejar cualquier excepción que pueda ocurrir al establecer el estilo
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dirCarpeta = new javax.swing.JTextField();
        seleccionArchivo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        facturas = new javax.swing.JTextField();
        Iniciar = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 249, 249));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel1.setText("Pdfs de salida");

        dirCarpeta.setEditable(false);
        dirCarpeta.setBackground(new java.awt.Color(255, 255, 255));
        dirCarpeta.setText("Downloads/pdfs");
        dirCarpeta.setFocusTraversalPolicyProvider(true);
        dirCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirCarpetaActionPerformed(evt);
            }
        });

        seleccionArchivo.setText("Archivo");
        seleccionArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionArchivoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel2.setText("Imagenes de facturas");

        facturas.setEditable(false);
        facturas.setBackground(new java.awt.Color(255, 255, 255));
        facturas.setFocusTraversalPolicyProvider(true);
        facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturasActionPerformed(evt);
            }
        });

        Iniciar.setText("Iniciar");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dirCarpeta, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(facturas, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(seleccionArchivo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(Iniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionArchivo)
                    .addComponent(facturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dirCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Iniciar)
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dirCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirCarpetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirCarpetaActionPerformed

    private void seleccionArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionArchivoActionPerformed

        JFileChooser fileChooser = new JFileChooser();
         fileChooser.setDialogTitle("Seleccionar carpeta");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        // Mostrar el diálogo de selección de archivos
        int result = fileChooser.showOpenDialog(this);
        
        // Si se selecciona un archivo, mostrar su ruta en el campo de texto
        if (result == JFileChooser.APPROVE_OPTION) {
            
            facturas.setText(fileChooser.getSelectedFile().getPath());}
    }//GEN-LAST:event_seleccionArchivoActionPerformed

    private void facturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facturasActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
        String rutaArchivo = facturas.getText();
        if (rutaArchivo.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                onIniciar( rutaArchivo);
            } catch (IOException ex) {
                Logger.getLogger(PanelGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_IniciarActionPerformed
 public void onIniciar( String rutaArchivo) throws IOException {
            Mavenproject1.descargarFacturas(rutaArchivo);
            JOptionPane.showMessageDialog(this, "Completado", "Éxito", JOptionPane.INFORMATION_MESSAGE);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JTextField dirCarpeta;
    private javax.swing.JTextField facturas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton seleccionArchivo;
    // End of variables declaration//GEN-END:variables
}
